"""
QUARK -- QUeued Asynchronous Request Keeper
test_main.py
Adam Zeloof
8/3/2026

This test suite was auto-generated by Google Gemini 3.1 Pro
"""

import os

import pytest
from fastapi.testclient import TestClient
from sqlmodel import Session, SQLModel, create_engine
from sqlmodel.pool import StaticPool

from main import app, get_session

# --- Test Setup & Fixtures ---

# 1. Create an in-memory SQLite database for testing
sqlite_url = "sqlite:///:memory:"
engine = create_engine(
    sqlite_url, 
    connect_args={"check_same_thread": False}, 
    poolclass=StaticPool
)

# 2. Dependency override to use the in-memory DB instead of quark_data.db
def get_session_override():
    with Session(engine) as session:
        yield session

app.dependency_overrides[get_session] = get_session_override

# 3. Initialize the TestClient and set the environment variable
os.environ["QUARK_API_KEY"] = "test_secret_key"
client = TestClient(app)

# 4. Setup the database before tests run
@pytest.fixture(autouse=True)
def setup_database():
    SQLModel.metadata.create_all(engine)
    yield
    SQLModel.metadata.drop_all(engine)

# --- The Test Suite ---

def test_auth_missing_key():
    response = client.get("/topics")
    assert response.status_code == 401
    assert response.json() == {"detail": "Invalid or missing API Key"}

def test_auth_invalid_key():
    response = client.get("/topics", headers={"X-API-Key": "wrong_key"})
    assert response.status_code == 401
    assert response.json() == {"detail": "Invalid or missing API Key"}

def test_submit_message():
    response = client.post(
        "/submit?topic=alerts",
        headers={"X-API-Key": "test_secret_key"},
        json={"alert_level": "high", "message": "Reactor temperature critical"}
    )
    assert response.status_code == 200
    data = response.json()
    assert data["status"] == "queued"
    assert data["topic"] == "alerts"
    assert data["id"] == 0  # Assuming 0-indexed as per your code logic

def test_get_messages():
    # Insert two messages
    headers = {"X-API-Key": "test_secret_key"}
    client.post("/submit?topic=logs", headers=headers, json={"log": "First"})
    client.post("/submit?topic=logs", headers=headers, json={"log": "Second"})

    # Fetch them back
    response = client.get("/messages?topic=logs", headers=headers)
    assert response.status_code == 200
    messages = response.json()
    
    assert len(messages) == 2
    
    # Check the custom outgoing formatting
    assert messages[0]["id"] == 0
    assert messages[0]["payload"]["log"] == "First"
    assert messages[1]["id"] == 1
    assert messages[1]["payload"]["log"] == "Second"
    assert "topic_sequence_id" not in messages[0] # Ensure it was excluded properly

def test_get_messages_with_max_index():
    headers = {"X-API-Key": "test_secret_key"}
    client.post("/submit?topic=chat", headers=headers, json={"text": "A"})
    client.post("/submit?topic=chat", headers=headers, json={"text": "B"})
    client.post("/submit?topic=chat", headers=headers, json={"text": "C"})

    # Only get up to index 1 (should return A and B, which are ids 0 and 1)
    response = client.get("/messages?topic=chat&max_index=1", headers=headers)
    messages = response.json()
    
    assert len(messages) == 2
    assert messages[-1]["id"] == 1

def test_get_topics():
    headers = {"X-API-Key": "test_secret_key"}
    client.post("/submit?topic=system", headers=headers, json={"status": "ok"})
    client.post("/submit?topic=ui", headers=headers, json={"click": "button"})

    response = client.get("/topics", headers=headers)
    assert response.status_code == 200
    topics = response.json()
    
    assert len(topics) == 2
    topic_names = [t["name"] for t in topics]
    assert "system" in topic_names
    assert "ui" in topic_names